INHERIT: mkdocs.yml

extra_css:
    - stylesheets/extra.css

plugins:
  - search
  - tags #insiders
  - git-revision-date-localized
  - macros:
      include_dir: macros
      j2_block_start_string: '@{%'
      j2_block_end_string: '%}'
      j2_variable_start_string: '@{{'
      j2_variable_end_string: '}}'
  - glightbox # enables image light box
  - social: #insiders
      cards_color:
        fill: "#1E61F0"
        text: "#FFFFFF"
      cards_font: IBM Plex Sans
  - privacy:
      external_links: true
      external_links_attr_map:
        target: _blank

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - tables
  - toc:
      permalink: true
      title: "On this page"
      toc_depth: 3
      permalink_title: Link to this section
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret # Enables super scripts
  - pymdownx.details # Enables collapsible admonitions
  - pymdownx.emoji: # Enables all sorts of emoji support
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight: # Enables code block syntax highlighting
      #anchor_linenums: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.keys # Enables inline key display
  - pymdownx.mark #
  - pymdownx.snippets # Enables snippets (content reuse)
  - pymdownx.smartsymbols
  - pymdownx.superfences: # Enables more nestable codeblocks
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed: # Enables content tabs
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
       kwds:
          case: lower
  - pymdownx.tasklist: # Enables task lists
      custom_checkbox: true
  - pymdownx.tilde # enables strikthrough (<del> tags) and subscripts https://facelessuser.github.io/pymdown-extensions/extensions/tilde/



# Long explanation for this extra doc.
# In order to use config inheritance, everything must use the alternative syntax (key:value vs lists)
# Lists are replaced wholesale with config inheritence.
# I couldn't get alternative syntax to work on mkdocs.yml without throwing constant errors and strange behavior.
# For now, mkdocs.yml plugins need to be all NON-insiders plugins, and insiders.mkdocs.yml is ALL plugins.
